import type { PlaceholderRegistry } from "./registry";

/**
 * Static placeholder registry data.
 * Generated from placeholder-registry.json.
 */
export const PLACEHOLDER_REGISTRY: PlaceholderRegistry = {
  description:
    "Registry of valid placeholder tokens used in the toolkit templates. Used by lint-placeholders to validate placeholder usage. The docs/ directory templates use additional granular placeholders not individually registered here - the linter auto-allows [UPPER_SNAKE_CASE] tokens in docs/ files.",
  categories: {
    project_identity: {
      tokens: {
        PROJECT_NAME: "Project display name",
        PROJECT_DESCRIPTION: "Brief project description",
        PROJECT_STATUS: "Current project status (e.g., MVP, Beta, Production)",
        PROJECT_BRIEF_PATH: "Path to project brief document",
        REPO_URL: "Git repository URL",
        TOOLKIT_VERSION: "Version of @outputease/toolkit that scaffolded this project",
      },
    },
    tech_stack: {
      tokens: {
        RUNTIME: "Runtime environment (e.g., node, bun, python, go)",
        RUNTIME_VERSION: "Required runtime version",
        PACKAGE_MANAGER: "Package manager (e.g., pnpm, npm, yarn, pip, cargo)",
        PACKAGE_MANAGER_VERSION: "Required package manager version",
        PM_VERSION: "Package manager version (short form)",
        FRAMEWORK: "Primary framework (e.g., Next.js, Astro, Django, Gin)",
        LANGUAGE: "Primary language (e.g., TypeScript, Python, Go, Rust)",
        STYLING: "CSS approach (e.g., Tailwind, CSS Modules, styled-components)",
        COMPONENT_LIBRARY: "UI component library (e.g., shadcn/ui, MUI, Radix)",
        LINTER_FORMATTER: "Code quality tools (e.g., Biome, ESLint+Prettier, Ruff)",
        LINTER: "Linter tool name",
        FORMATTER: "Formatter tool name",
        LINTER_CONFIG: "Linter configuration file path",
        FORMATTER_CONFIG: "Formatter configuration file path",
        TECH_STACK_SUMMARY: "One-line tech stack summary",
        VERSION: "Framework or library version",
      },
    },
    commands: {
      tokens: {
        DEV_COMMAND: "Dev server start command",
        BUILD_COMMAND: "Production build command",
        TEST_COMMAND: "Test runner command",
        LINT_COMMAND: "Lint command",
        INSTALL_COMMAND: "Dependency install command",
        FORMATTER_COMMAND: "Auto-format command for settings.json hook",
        SECURITY_SCAN_COMMAND: "Security audit command",
        DB_SETUP_COMMAND: "Database setup command",
        DB_MIGRATE_COMMAND: "Database migration command",
        DB_SEED_COMMAND: "Database seed command",
        AUDIT_COMMAND: "Dependency audit command",
        FORMAT_ON_SAVE_OR_REMOVE: "Format-on-save instruction or remove if N/A",
      },
    },
    paths: {
      tokens: {
        SOURCE_DIR: "Source code root directory (e.g., src/, lib/, app/)",
        COMPONENTS_DIR: "Components directory",
        UI_PRIMITIVES_DIR: "UI primitive components directory",
        SHARED_COMPONENTS_DIR: "Shared components directory",
        FEATURE_COMPONENTS_DIR: "Feature-specific components directory",
        PAGES_DIR: "Pages/routes directory",
        LIB_DIR: "Library/utilities directory",
        STYLES_DIR: "Stylesheets directory",
        PUBLIC_DIR: "Public/static assets directory",
        PUBLIC_DIR_OR_REMOVE: "Public directory path or remove if N/A",
        TEST_DIR: "Test files directory",
        TYPES_DIR: "Type definitions directory",
        ROUTES_DIR: "Routes directory",
        ROUTES_DIR_OR_REMOVE: "Routes directory or remove if N/A",
        PROJECT_ROOT: "Project root description",
        PROJECT_TREE: "Directory tree diagram",
        PATH_ALIASES: "Path alias configuration",
        CONFIG_FILES: "Configuration files list",
        BUILD_CACHE_DIR: "Build cache directory",
        E2E_DIR: "End-to-end test files directory",
      },
    },
    file_patterns: {
      tokens: {
        EXT: "File extension (e.g., tsx, jsx, py, rs, go)",
        SOURCE_EXTENSIONS: "Source file extensions regex (e.g., ts|tsx|js|jsx)",
        FRONTEND_EXTENSIONS: "Frontend file extensions regex (e.g., tsx|jsx|vue|svelte|astro)",
        BUILD_LINT_PATTERN: "Build/lint transcript detection pattern",
        TEST_RUNNER: "Test framework import (e.g., bun:test, vitest, pytest)",
      },
    },
    project_principles: {
      tokens: {
        PRINCIPLE_1: "First core project principle",
        PRINCIPLE_2: "Second core project principle",
        PRINCIPLE_3: "Third core project principle",
        CONSTRAINT_1: "First key constraint",
        CONSTRAINT_2: "Second key constraint",
        NEVER_DO_1: "First prohibition",
        NEVER_DO_2: "Second prohibition",
        ALWAYS_DO_1: "First required behavior",
        ALWAYS_DO_2: "Second required behavior",
      },
    },
    troubleshooting: {
      tokens: {
        GOTCHA_CATEGORY_1: "First gotcha category",
        GOTCHA_DESCRIPTION_1: "First gotcha description",
        EXACT_FIX_1: "First gotcha fix",
        GOTCHA_CATEGORY_2: "Second gotcha category",
        GOTCHA_DESCRIPTION_2: "Second gotcha description",
        EXACT_FIX_2: "Second gotcha fix",
        COMMON_ISSUE_1: "First common issue name",
        WHAT_GOES_WRONG: "What goes wrong description",
        FIX_COMMAND: "Fix command",
        COMMON_ISSUE_2: "Second common issue name",
      },
    },
    extensibility: {
      tokens: {
        ADDITIONAL_SETUP_STEPS: "Additional environment setup steps",
        ADDITIONAL_COMMANDS_OR_REMOVE: "Additional commands or remove section",
        ADDITIONAL_DIR_OR_REMOVE: "Additional directory or remove",
        ADDITIONAL_ENV_VARS: "Additional environment variables",
        ADDITIONAL_FONT_OR_REMOVE: "Additional font or remove",
        ADDITIONAL_COMPONENT_OR_REMOVE: "Additional component or remove",
        ADDITIONAL_DECISION_OR_REMOVE: "Additional architectural decision or remove",
        ADDITIONAL_PREREQUISITES_OR_REMOVE: "Additional prerequisites or remove",
      },
    },
    documentation: {
      tokens: {
        DATE: "Date in YYYY-MM-DD format",
        DESCRIPTION: "Generic description field",
        ARCHITECTURE_DESCRIPTION: "Architecture overview description",
        RELEASE_DATE: "Release/setup date in YYYY-MM-DD format",
      },
    },
    infrastructure: {
      tokens: {
        HOSTING_PROVIDER: "Hosting service provider",
        PRODUCTION_URL: "Production URL",
        PROD_BRANCH: "Production branch name",
        DEFAULT_BRANCH: "Default git branch name",
        CI_PLATFORM: "CI/CD platform",
        CI_SECRETS_PROVIDER: "CI secrets management provider",
        CI_SECRETS_METHOD: "How CI accesses secrets",
        STAGING_SECRETS_METHOD: "How staging accesses secrets",
        STAGING_ACCESS: "Staging access method",
        STAGING_URL: "Staging URL",
        DATABASE_OR_REMOVE: "Database name or remove section if no database",
        AUTH_PROVIDER_OR_REMOVE: "Auth provider name or remove section if no auth",
        STAGING_ENV_OR_REMOVE: "Staging environment or remove",
        PROD_SECRETS_METHOD: "How production accesses secrets",
        PROD_ACCESS: "Production access method",
        DEPENDABOT_OR_RENOVATE_OR_REMOVE: "Dependency update tool or remove",
        ROTATION_FREQUENCY: "Secret rotation frequency",
        SECRET_ROTATION_PROCEDURE: "Secret rotation procedure",
      },
    },
    security: {
      tokens: {
        SECURITY_EMAIL: "Security contact email",
        LATEST_MAJOR: "Latest supported major version",
        PREVIOUS_MAJOR: "Previous supported major version",
      },
    },
    contributing: {
      tokens: {
        REVIEW_COUNT: "Required review count for PRs",
        REVIEW_SLA: "Review turnaround time SLA",
        MAINTAINER_CONTACT: "Maintainer contact info",
        LICENSE_TYPE: "Project license type",
      },
    },
    features: {
      tokens: {
        FEATURE_1: "First key feature description",
        FEATURE_2: "Second key feature description",
        FEATURE_3: "Third key feature description",
        INITIAL_FEATURE_1: "First initial feature for changelog",
        INITIAL_FEATURE_2: "Second initial feature for changelog",
      },
    },
    design: {
      tokens: {
        BRAND_VOICE_DESCRIPTION: "Brand voice description",
        LOGO_PATH: "Logo file path",
        MIN_SIZE_PX: "Minimum logo size in pixels",
        FAVICON_PATH: "Favicon file path",
        PRIMARY_HEX: "Primary color hex",
        PRIMARY_DARK_HEX: "Primary dark variant hex",
        PRIMARY_LIGHT_HEX: "Primary light variant hex",
        BG_HEX: "Background color hex",
        SURFACE_HEX: "Surface color hex",
        TEXT_PRIMARY_HEX: "Primary text color hex",
        TEXT_MUTED_HEX: "Muted text color hex",
        BORDER_HEX: "Border color hex",
        SUCCESS_HEX: "Success color hex",
        WARNING_HEX: "Warning color hex",
        DESTRUCTIVE_HEX: "Destructive/error color hex",
        HEADING_FONT: "Heading font family",
        BODY_FONT: "Body font family",
        MONO_FONT: "Monospace font family",
        FONT_STACK: "Font stack CSS value",
        RADIUS: "Border radius value",
        SPACING_TOKEN: "Spacing token name",
        SIZE_TARGET: "Performance size target",
        TOKEN: "Design token name",
        NOTES: "Design token notes",
      },
    },
    api: {
      tokens: {
        API_PURPOSE_SUMMARY: "API purpose summary",
        DEV_PORT: "Development server port",
        PRODUCTION_DOMAIN: "Production API domain",
        HTTP_METHOD: "HTTP method",
        RESOURCE: "API resource name",
        RESOURCE_2: "Second API resource name",
        ENDPOINT_DESCRIPTION: "Endpoint description",
        PARAM: "Parameter name",
        FIELD: "Field name",
        FIELD_1: "First field name",
        FIELD_2: "Second field name",
        TYPE: "Field type",
        VALUE: "Field value",
        METHOD: "Method name",
        GENERATED_ID: "Auto-generated ID example",
        RATE_LIMIT_AUTH: "Authenticated rate limit",
        RATE_LIMIT_UNAUTH: "Unauthenticated rate limit",
        WINDOW: "Rate limit window",
        ENDPOINT_SPECIFIC_OR_REMOVE: "Endpoint-specific limit or remove",
        LIMIT: "Rate limit value",
      },
    },
    auth: {
      tokens: {
        AUTH_SECRET_VAR: "Auth secret environment variable name",
        DATABASE_URL_VAR: "Database URL environment variable name",
        API_URL_VAR: "API URL environment variable name",
        DATABASE: "Database system name",
        DB_VERSION: "Database version",
        SERVICE_API_KEY: "Third-party service API key variable name",
      },
    },
    conventions: {
      tokens: {
        CSS_NAMING_CONVENTION: "CSS naming convention",
        CSS_CLASS_EXAMPLE: "CSS class example",
        VALIDATION_LIBRARY: "Form validation library",
        WCAG_LEVEL: "WCAG compliance level",
        CONTRAST_RATIO: "Minimum contrast ratio",
        SSR_SSG_CSR: "Rendering strategy",
        RATIONALE: "Architectural decision rationale",
        STATE_SOLUTION: "State management solution",
        DATA_LAYER: "Data access layer",
        UI_LIBRARY: "UI library name",
        FORM_LIBRARY_OR_REMOVE: "Form library or remove if N/A",
        TEST_FRAMEWORK: "Test framework name",
      },
    },
    layout: {
      tokens: {
        HEADER_ACTIONS_OR_REMOVE: "Header actions or remove",
        FOOTER_CONTENT: "Footer content description",
        USAGE: "Usage description",
        PORT: "Port number",
        YES_OR_NO: "Boolean flag",
        ENV_TEST_OR_REMOVE: "Test environment config or remove",
        RGB_VALUES: "RGB color values",
        WORK_DESCRIPTION: "Work description",
        PHASE_DESCRIPTION: "Phase description",
        CATEGORY: "Category label",
        STATUS: "Status label",
        PRIORITY_1: "First priority item",
        NEXT_1: "First next action",
        FRAMEWORK_IMPORTS: "Framework import statements",
        COMPONENT_LIBRARY_IMPORTS: "Component library imports",
        PROPS_DEFINITION: "Props type/interface definition",
        EXPORT_CONVENTION: "Export convention (export default, export const, etc.)",
      },
    },
  },
  known_non_tokens: {
    description: "Patterns that look like tokens but are not. The linter skips these.",
    single_letter_regex: "^[A-Z]{1,2}$",
    literals: ["X", "N", "Y", "YYYY-MM-DD", "XXX", "PLACEHOLDER"],
  },
  framework_terms_blocklist: [
    "Next.js",
    "next.js",
    "nextjs",
    "Astro",
    "React",
    "Vue",
    "Svelte",
    "Angular",
    "Django",
    "Flask",
    "Rails",
    "Express",
    "Tailwind",
    "shadcn",
    "bun run",
    "npm run",
    "pnpm run",
    "yarn run",
    "node_modules",
    "Supabase",
    "Drizzle",
    "Prisma",
    "FastAPI",
    "Mongoose",
    "NestJS",
    "Nuxt",
    "Remix",
    "Sequelize",
    "SvelteKit",
    "Turbopack",
    "TypeORM",
    "Vite",
  ],
  removal_hints: {
    description:
      "For _OR_REMOVE tokens that appear inline (not as table rows or bullets), these hints specify the exact text to strip when the token is removed.",
    HEADER_ACTIONS_OR_REMOVE: {
      scope: "inline",
      pattern: ", [HEADER_ACTIONS_OR_REMOVE]",
    },
    ENV_TEST_OR_REMOVE: {
      scope: "inline",
      pattern: " [ENV_TEST_OR_REMOVE]",
    },
    CODE_SPLIT_OR_REMOVE: {
      scope: "inline",
      pattern: " [CODE_SPLIT_OR_REMOVE]",
    },
    BUNDLE_BUDGET_TOOL_OR_REMOVE: {
      scope: "inline",
      pattern: "[BUNDLE_BUDGET_TOOL_OR_REMOVE]",
    },
  },
  notes: {
    OR_REMOVE_suffix:
      "Tokens ending in _OR_REMOVE indicate optional sections. If not applicable, remove the entire section rather than leaving the placeholder.",
    contextual_examples:
      "Framework names appearing as examples in lists (e.g., 'Examples: node, bun, python') are acceptable. The blocklist targets hardcoded usage, not illustrative examples.",
  },
};
